/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moneymanager.screens.overview;

import moneymanager.constants.TransactionPanelActionListener;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author donla
 */
public class TransactionWindow extends javax.swing.JPanel {
    private JTextField amountField;
    private String transactionType;
    private TransactionPanelActionListener actionListener;
    //private TransactionPanelActionListener actionListener;
    /**
     * Creates new form TransactionWindow
     */
    public TransactionWindow(String transactionType, TransactionPanelActionListener actionListener) {
        this.transactionType = transactionType;
        this.actionListener = actionListener;
        initComponents();
        init();
    }

    public void init(){
        JLabel label = new JLabel("Enter: " + transactionType + "Amount");
        amountField = new JTextField(10);

        JButton confirmButton = new JButton("Confirm");
        confirmButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                double amount = getAmount();
                actionListener.onConfirm(amount);
                closeDialog();
            }
        });

        JButton cancelButton = new JButton("Cancel");
        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actionListener.onCancel();
                closeDialog();
            }
        });

        add(label);
        add(amountField);
        add(confirmButton);
        add(cancelButton);
    }

    private double getAmount() {
        String amountText = amountField.getText();
        return Double.parseDouble(amountText);
    }

    private void closeDialog() {
        SwingUtilities.getWindowAncestor(this).dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
