/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moneymanager.screens.history;

import moneymanager.model.MoneyModel;
import moneymanager.model.TransactionModel;
import moneymanager.screens.overview.Overview2;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author donla
 */
public class History extends javax.swing.JPanel {
    private TransactionModel transactionModel;
    private int index;
    private MoneyModel moneyModel;
    Overview2 overview;

    public void setCurrencySign(String currencySign) {
        this.currencySign.setText(currencySign);
    }

    public void setCurrentBalance(String currentBalance) {
        this.currentBalance.setText(currentBalance);
    }

    public void setTransactionModel(TransactionModel transactionModel) {
        this.transactionModel = transactionModel;
    }

    /**
     * Creates new form History
     */
    public History() {
//        overview = new Overview2("");
        index = 0;
        initComponents();
        init();
    }

    public void init(){
//        currencySign.setText(overview.getCurrencySign());
//        currentBalance.setText(String.valueOf(overview.getBalance()));
    }

    public void showTransactionHistory(){
        textArea.append(transactionModel.getTransactionHistory().get(index));
        index++;
        repaint();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        currencySign = new javax.swing.JLabel();
        currentBalance = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        currencySign.setFont(new java.awt.Font("Dialog", 0, 45)); // NOI18N
        currencySign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currencySign.setText("jLabel1");
        currencySign.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(currencySign);

        currentBalance.setFont(new java.awt.Font("Dialog", 0, 45)); // NOI18N
        currentBalance.setText("jLabel1");
        currentBalance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(currentBalance);

        textArea.setBackground(new java.awt.Color(255, 255, 255));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(0, 0, 0));
        textArea.setRows(5);
        textArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(textArea);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jLabel1.setText("Account Balance");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(430, 20, 260, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1310, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currencySign;
    private javax.swing.JLabel currentBalance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
