/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moneymanager.main;

import moneymanager.customs.CustomFadingPanel;
import moneymanager.model.MoneyModel;
import moneymanager.model.TransactionModel;
import moneymanager.screens.history.History;
import moneymanager.screens.overview.Overview2;
import moneymanager.constants.Colors;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author donla
 */
public class Main2 extends javax.swing.JFrame {
    private CardLayout cardLayout;
    private TransactionModel transactionModel;
    private MoneyModel moneyModel;
    private History historyScreen;

    /**
     * Creates new form Main2
     */

    // Make a documentation based on the code below
    public Main2() {
        setResizable(false);
        historyScreen = new History();
        moneyModel = new MoneyModel(2700, "₱", 1, -1);
        transactionModel = new TransactionModel();
        initComponents();
        setTitle("Peddy Bank");
        cardLayout = (CardLayout) mainBody.getLayout();
        mainBody.add(new Overview2(moneyModel, transactionModel, historyScreen), "Screen1");
        mainBody.add(historyScreen, "Screen2");
        cardLayout.show(mainBody, "Show");
    }

    public Main2(String dummy){

    }

    public void switchScreen(String panelName){
        CustomFadingPanel fadingPanel = new CustomFadingPanel();
        mainBody.add(fadingPanel, "FadingPanel");
        cardLayout.show(mainBody, "FadingPanel");

        Timer timer = new Timer(200, (e) -> {
           fadingPanel.startFadeOut();
           cardLayout.show(mainBody, panelName);
        });
        timer.setRepeats(false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBody = new javax.swing.JPanel();
//        overview22 = new moneymanager.screens.overview.Overview2();
        bottomBar = new javax.swing.JPanel();
        homeButton = new moneymanager.customs.CustomButton3();
        transactionHistoryButton = new moneymanager.customs.CustomButton3();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 600));

        mainBody.setLayout(new java.awt.CardLayout());
//        mainBody.add(overview22, "card2");

        bottomBar.setBackground(Colors.secondaryColor);
        bottomBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 10));

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        bottomBar.add(homeButton);

        transactionHistoryButton.setText("Transactions");
        transactionHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionHistoryButtonActionPerformed(evt);
            }
        });
        bottomBar.add(transactionHistoryButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottomBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomBar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        switchScreen("Screen1");
    }//GEN-LAST:event_homeButtonActionPerformed

    private void transactionHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionHistoryButtonActionPerformed
        switchScreen("Screen2");
    }//GEN-LAST:event_transactionHistoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomBar;
    private moneymanager.customs.CustomButton3 homeButton;
    private javax.swing.JPanel mainBody;
    private moneymanager.screens.overview.Overview2 overview22;
    private moneymanager.customs.CustomButton3 transactionHistoryButton;
    // End of variables declaration//GEN-END:variables
}